name: ''xxxx''
version: 1


libraries:
- name: django
  version: "1.4"
handlers:
- url: /static
  static_dir: static


cron:
- description: cron_clean
  url: /admin/root/weibo/clean
  schedule: "0 0 * * 0"