---
name: pythonweibo
version: 1
accesskey: 4x2n5kw2j1
worker: tornado
libraries:
- name: tornado
  version: "2.4.1"
cron:
- description: cron sync
  url: sync
  schedule: every 5 mins
  timezone: Beijing